# Generated by Django 5.1.5 on 2025-02-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, verbose_name='Номер квартири')),
                ('floor', models.CharField(max_length=9, verbose_name='Поверх')),
                ('room_amount', models.CharField(max_length=3, verbose_name='Кількість кімнат')),
                ('bought', models.BooleanField(verbose_name='Куплена (так/ні)')),
                ('residents_amount', models.IntegerField(default=0, verbose_name='Кількість мешканців')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=25, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=50, verbose_name='Фамілія')),
                ('phone_number', models.CharField(max_length=19, unique=True, verbose_name='Номер телефону')),
                ('password', models.CharField(max_length=19, verbose_name='Пароль')),
                ('has_pet', models.BooleanField(default=False, verbose_name='Маю улюбленця')),
                ('pet_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид улюбленця')),
                ('has_car', models.BooleanField(default=False, verbose_name='Маю машину')),
                ('car_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель машини')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='resident.flat', verbose_name='Квартира')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
