# Generated by Django 5.1.5 on 2025-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='username',
            field=models.CharField(default='xxxx', max_length=50, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
